bbs/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^bulletinboard/', include('bulletinboard.urls', namespace="bulletinboard")),
    url(r'', include('social_auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url('^markdown/', include('django_markdown.urls')),
    url(r'^accounts/login/$', 'bulletinboard.views.login_user'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/accounts/login/'}),
    url(r'^accounts/newUser/$', 'bulletinboard.views.new_user'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bulletinboard/urls.py
from django.conf.urls import patterns, url
from bulletinboard import views


urlpatterns = patterns(
    '',
    url(r'^$', views.home, name="home"),
    url(r'^(?P<board_id>\d+)/delete/$', views.delete_board, name="delete_board"),
    url(r'^(?P<board_id>\d+)/moveup/$', views.move_up, name="move_up"),
    url(r'^(?P<board_id>\d+)/movedown/$', views.move_down, name="move_down"),
    url(r'^(?P<board_id>\d+)/$', views.board, name="board"),
    url(r'^(?P<board_id>\d+)/thread/(?P<thread_id>\d+)/$', views.thread, name="thread"),
    url(r'^userprofile/$', views.user_profile, name="user_profile"),
    url(r'^editprofile/$', views.edit_user_profile, name="edit_user_profile"),
    url(r'^editprofile/submit/$', views.submit_user_profile, name="submit_user_profile"),
    url(r'^profiles/(?P<user_id>\d+)/$', views.other_profile, name="other_profile"),
    url(r'^profiles/(?P<user_id>\d+)/ban/$', views.ban_user, name="ban_user"),
    url(r'^(?P<board_id>\d+)/thread/(?P<thread_id>\d+)/lockunlock/$', views.lock_unlock_thread, name="lock_unlock_thread"),
    url(r'^(?P<board_id>\d+)/thread/(?P<thread_id>\d+)/sticky/$', views.sticky_not_sticky, name="sticky_not_sticky"),
    url(r'^(?P<board_id>\d+)/thread/(?P<thread_id>\d+)/post/(?P<post_id>\d+)/$', views.edit_post, name="edit_post"),
    url(r'^(?P<board_id>\d+)/thread/(?P<thread_id>\d+)/post/(?P<post_id>\d+)/submit/$', views.submit_post, name="submit_post"),
    url(r'^(?P<board_id>\d+)/thread/(?P<thread_id>\d+)/delete/$', views.delete_thread, name="delete_thread"),
)

bulletinboard/models.py
from django.db import models
from django.contrib.auth.models import User, Permission

import markdown

MAX_LENGTH_CHAR = 50
MAX_LENGTH_TYPE = 1


class UserProfile(models.Model):
    USER_TYPES = [
        [1, 'Poster'],
        [2, 'Moderator'],
        [3, 'Administrator'],
    ]

    GENDER_CHOICES = [
        [1, 'Female'],
        [2, 'Male'],
    ]

    user = models.ForeignKey(User, unique=True)
    user_type = models.IntegerField(max_length=MAX_LENGTH_TYPE, choices=USER_TYPES, default=1)
    is_banned = models.BooleanField(default=False)
    avatar = models.ImageField(upload_to='avatars/', null=True)
    about_me = models.TextField()
    birthdate = models.DateField()
    hometown = models.CharField(max_length=MAX_LENGTH_CHAR)
    present_location = models.CharField(max_length=MAX_LENGTH_CHAR)
    skype = models.CharField(max_length=MAX_LENGTH_CHAR, blank=True)
    ym = models.CharField(max_length=MAX_LENGTH_CHAR, blank=True)
    website = models.CharField(max_length=MAX_LENGTH_CHAR, blank=True)
    gender = models.IntegerField(max_length=MAX_LENGTH_TYPE, choices=GENDER_CHOICES, default=1)
    interests = models.TextField(blank=True)

    class Meta:
        permissions = (
            ("ban_user", "Can ban user"),
        )

    def save(self):
        add_post = Permission.objects.get(name='Can add post')
        edit_post = Permission.objects.get(name='Can change post')
        add_thread = Permission.objects.get(name='Can add thread')
        edit_thread = Permission.objects.get(name='Can change thread')
        ban_user = Permission.objects.get(name='Can ban user')
        lock_thread = Permission.objects.get(name='Can lock thread')
        thread_type = Permission.objects.get(name='Can change threadtype')
        add_board = Permission.objects.get(name='Can add board')
        delete_board = Permission.objects.get(name='Can delete board')
        edit_board = Permission.objects.get(name='Can change board')
        add_topic = Permission.objects.get(name='Can add topic')
        edit_topic = Permission.objects.get(name='Can change topic')
        delete_topic = Permission.objects.get(name='Can delete topic')
        delete_thread = Permission.objects.get(name='Can delete thread')

        self.user.user_permissions.clear()

        if self.user_type == 1:
            self.user.is_staff = False
            self.user.user_permissions.add(add_post, edit_post, add_thread,
                                           edit_thread, delete_thread)
        elif self.user_type == 2:
            self.user.is_staff = False
            self.user.user_permissions.add(add_post, edit_post, add_thread,
                                           edit_thread, delete_thread, ban_user, lock_thread,
                                           thread_type)
        else:
            self.user.is_staff = True
            self.user.user_permissions.add(add_post, edit_post, add_thread, edit_thread,
                                           ban_user, lock_thread, thread_type, add_topic,
                                           edit_topic, delete_topic, add_board, delete_board,
                                           edit_board, delete_thread
                                           )
        self.user.save()
        super(UserProfile, self).save()

    def get_gender(self):
        return self.GENDER_CHOICES[self.gender-1][1]

    def get_type(self):
        return self.USER_TYPES[self.user_type-1][1]

    def get_post_count(self):
        posts = self.post_set.all()
        number = 0
        for post in posts:
            number = number + 1
        return number
    get_post_count.short_description = "Total Post Count"

    def __unicode__(self):
        return self.user.username


class Topic(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR)

    def get_board_number(self):
        boards = self.board_set.all()
        number = 0
        for board in boards:
            number = number+1
        return number
    get_board_number.short_description = "Number of Boards"

    def __unicode__(self):
        return self.name


class Board(models.Model):
    name = models.CharField(max_length=MAX_LENGTH_CHAR)
    icon = models.ImageField(upload_to='icons/', null=True)
    description = models.TextField()
    topic = models.ForeignKey(Topic)
    rank = models.SmallIntegerField(unique=True, db_index=True)

    def get_thread_number(self):
        threads = self.thread_set.all()
        number = 0
        for thread in threads:
            number = number+1
        return number
    get_thread_number.short_description = "Number of Threads"

    def get_post_number(self):
        threads = self.thread_set.all()
        number = 0
        for thread in threads:
            posts = thread.post_set.all()
            for post in posts:
                number = number+1
        return number
    get_post_number.short_description = "Number of Posts"

    def increase_rank(self):
        """
        Changes position of this item with the next item in the
        list. Does nothing if this item is the last one.
        """
        try:
            next_item = Board.objects.filter(rank__gt=self.rank)[0]
        except IndexError:
            pass
        else:
            self.swap_ranks(next_item)

    def decrease_rank(self):
        """
        Changes position of this item with the previous item in the
        list. Does nothing if this item is the first one.
        """
        try:
            prev_item = Board.objects.filter(rank__lt=self.rank).reverse()[0]
        except IndexError:
            pass
        else:
            self.swap_ranks(prev_item)

    def swap_ranks(self, other):
        """
        Swap positions with ``other`` board.
        """
        maxrank = Board.objects.reverse()[0].rank + 1
        prev_rank, self.rank = self.rank, maxrank
        self.save()
        self.rank, other.rank = other.rank, prev_rank
        other.save()
        self.save()

    class Meta:
        ordering = ('rank',)

    def __unicode__(self):
        return self.name


class Thread(models.Model):
    THREAD_TYPE = [
        ['1', 'Sticky'],
        ['2', 'Non-sticky'],
    ]

    name = models.CharField(max_length=MAX_LENGTH_CHAR)
    date_created = models.DateField(auto_now_add=True)
    user = models.ForeignKey(UserProfile)
    board = models.ForeignKey(Board)
    thread_type = models.CharField(max_length=MAX_LENGTH_TYPE, choices=THREAD_TYPE, default=2)
    is_locked = models.BooleanField(default=False)

    def get_post_number(self):
        posts = self.post_set.all()
        number = 0
        for post in posts:
            number = number+1
        return number
    get_post_number.short_description = "Number of Posts"

    class Meta:
        ordering = ('thread_type',)
        permissions = (
            ("lock_thread", "Can lock thread"),
            ("change_threadtype", "Can change threadtype")
        )

    def __unicode__(self):
        return self.name


class Post(models.Model):
    user = models.ForeignKey(UserProfile)
    thread = models.ForeignKey(Thread)
    message = models.TextField('Message Body as HTML', blank=True)
    message_markdown = models.TextField('Message Body')
    date_posted = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('date_posted',)

    def save(self):
        self.message = markdown.markdown(self.message_markdown)
        super(Post, self).save()

    def __unicode__(self):
        return "%s's post" % self.user.user.username

bulletinboard/forms.py
from django.forms import ModelForm
from bulletinboard.models import UserProfile, Board, Thread, Post, Topic


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user', 'user_type', 'is_banned')


class TopicForm(ModelForm):
    class Meta:
        model = Topic


class BoardForm(ModelForm):
    class Meta:
        model = Board
        exclude = ('rank',)


class ThreadForm(ModelForm):
    class Meta:
        model = Thread
        exclude = ('is_locked', 'user', 'board', 'thread_type', 'date_created')


class PostForm(ModelForm):
    class Meta:
        model = Post
        exclude = ('user', 'date_posted', 'thread', 'message')

bulletinboard/templates/bulletinboard/boardIndex.html
{% extends "bulletinboard/base.html" %}
{% block title %} Board Index - {{board.name}}{% endblock %}
{% block body %}
    <header class="board-header">
        <a href="/bulletinboard/" class="link"> Home </a>
        >
        <a class="board-header-name">{{board.name}}</a>
        &nbsp;<img src="{{MEDIA_URL}}{{board.icon}}" alt="Board Icon" class="header-board-icon" />
        {% if perms.bulletinboard.delete_board and profile.is_banned == False %}
            <a href="{% url 'bulletinboard:delete_board' board.id %}">
                <img src="{{STATIC_URL}}images/trash.png" alt="Delete Board" class="delete-board-button" title="Delete Board" />
            </a>
        {% endif %}
    </header>   
    {% if threads %}
    <section>
            <br />
            <table class="thread-list">
            <thead>
                <tr>
                    <th class='thread-name'>Thread</th>
                    <th>Author</th>
                    <th>Posts</th>
                    <th>Last Reply</th>
                </tr>
            </thead>
            <tbody>
            {% load bulletinboard_filters %}
            {% for thread, post in threads|zip:posts %}
                <tr>
                    <td class='thread-name'>
                        {% if thread.thread_type == '1' %}
                            <img src="{{STATIC_URL}}images/pin.png" class="thread-type-image" />
                        {% endif %}
                        {% if thread.is_locked %}
                            <img src="{{STATIC_URL}}images/lock.png" class="thread-type-image" />
                        {% endif %}
                        <a class="link" href="{% url 'bulletinboard:thread' board.id thread.id %}">
                            {{thread.name}}
                        </a>
                    </td>
                    <td>
                        <a class="link" href="{% url 'bulletinboard:other_profile' thread.user.id %}">
                            {{thread.user.user}}
                        </a>
                    </td>
                    <td>{{thread.get_post_number}}</td>
                    <td>
                        <a class="link" href="{% url 'bulletinboard:other_profile' post.user.id %}">
                            {{post.user.user.username}}
                        </a>
                        on {{thread.latest_post}}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <section class="pagination">
            <form method="post" action="">
                {% csrf_token %}
                Go to page: 
                <select name="pagenumber">
                {% for page in threads.paginator.num_pages|get_range %}
                    <option value="{{page}}">{{page}}</option>
                {% endfor %}
                <select>
                <input type="submit" value=">>" name="gotopage" />
            </form>
        </section>
    </section>
    {% else %}
        <section class="empty-thread">
            <h2 class="no-list">No threads for this board.</h2>
        </section>
    {% endif %}
    
    <!-- check if the user is banned, if not, display the forms for creating threads and posts -->
    {% if profile.is_banned == False %}
        <section class='new-thread-form'>
            <hr />
            <h2 class="new-form-header">Add New Thread and Post:</h2>
            <hr />
            <br />
            <form action="" method="post">
                {% csrf_token %}
                <table>
                {{thread_form.as_table}}
                {{post_form.as_table}}
                </table>
                <input type="submit" value="Add Thread and Post" name="addthreadpost" />
            </form>
        </section>
    {% else %}
        <section class="banned">
            <h2 class="no-list">
                <img src="{{STATIC_URL}}images/banned.png"  class="header-image-button" alt="Banned" />
                You are banned from creating threads and adding posts.
            </h2>
        </section>
    {% endif %}
    
{% endblock %}

bulletinboard/templates/bulletinboard/editPost.html
{% extends "bulletinboard/base.html" %}
{% block title %} Edit Post {% endblock %}
{% block body %}
    <header class="board-header">
        <a href="/bulletinboard/" class="link"> Home </a>
        >
        <a href="{% url 'bulletinboard:board' post.thread.board.id %}" class="link">{{post.thread.board.name}}</a>
        &nbsp;<img src="{{MEDIA_URL}}{{post.thread.board.icon}}" alt="Board Icon" class="header-board-icon" />&nbsp;
        >
        <a href="{% url 'bulletinboard:thread' post.thread.board.id post.thread.id %}" class="link">
            {{post.thread.name}}
        </a>
    </header>
    <br />
    <section class="edit-post-form">
    <form action="{% url 'bulletinboard:submit_post' post.thread.board.id post.thread.id post.id %}" method="POST">
        {% csrf_token %}
        <table>{{form.as_table}}</table>
        <input type="submit" value="Edit Post" />
    </form>
    </section>
    <br />
{% endblock %}

bulletinboard/templates/bulletinboard/editProfile.html
{% extends "bulletinboard/base.html" %}
{% block title %} Edit User Profile {% endblock %}
{% block body %}
    <section>
        <header class="user-profile-header">
            <img src="{{MEDIA_URL}}{{profile.avatar}}" class="user-profile-avatar"/>
            About
        </header>
    </section>
    <section class="user-profile-form">
        <form action="{% url 'bulletinboard:submit_user_profile' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <br />
            <table>{{form.as_table}}</table>
            <input type="submit" value="Edit Profile" />
        </form>
    </section>
{% endblock %}

bulletinboard/templates/bulletinboard/home.html
{% extends "bulletinboard/base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
    {% if boards %}
    {% for header, entries in boards.iteritems %}
        <article>
            <div class="list-of-boards">
                <h2 class="next-line">
                    {{header}}
                    <hr />
                </h2>
                <br />
                {% for board in entries %}
                    <div class="board-display">
                        {% if profile.user_type == 3 %}
                            <a href="{% url 'bulletinboard:move_up' board.id %}" title="Move left">
                                <img class="reorder-board-button" src="{{STATIC_URL}}images/left.png" />
                            </a>
                        {% endif %}
                        <img class="board-icon" src="{{MEDIA_URL}}{{board.icon}}" />
                        {% if profile.user_type == 3 %}
                            <a href="{% url 'bulletinboard:move_down' board.id %}" title="Move right">
                                <img class="reorder-board-button" src="{{STATIC_URL}}images/right.png" />
                            </a>
                        {% endif %}
                        <div class="board-name-details">
                            <a href="{% url 'bulletinboard:board' board.id %}" class="board-name">
                                {{board.name}}
                            </a>
                            <div class="board-details">
                                <p>{{board.description}}</p>
                                <ul class="board-details-list">
                                    <li><a class="thread-post-number">Threads:</a> {{board.get_thread_number}}</li>
                                    <li><a class="thread-post-number">Posts:</a> {{board.get_post_number}}</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </article>
    {% endfor %}
    {% else %}
        <article class="empty-board">
            <h3 class="no-list">There are no boards yet.</h3>
        </article>
    {% endif %}
    {% if perms.bulletinboard.add_topic %}
        {% if profile.is_banned == False %}
        <section class="topic-form">
            <h1 class="new-form-header">
                <hr />
                Add Topic:
                <hr />
            </h1>
            <form action="" method="post">
                {% csrf_token %}
                <p>
                {{topic_form.as_p}}
                <input type="submit" value="Add Topic" name="addtopic"/>
                </p>
            </form>
        </section>
        <section class="board-form">
            <h1 class="new-form-header">
                <hr />
                Add Board:
                <hr />
            </h1>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p>
                    {{board_form.as_p}}
                    <input type="submit" value="Add Board" name="addboard" />
                </p>
            </form>
        </section>
        {% else %}
        <section class="banned-user">
            <h3 class="no-list">
                <img src="{{STATIC_URL}}images/banned.png" class="header-image-button" />
                You are banned from creating topics and boards.
            </h3>
        </section>
        {% endif %}
    {% endif %}
{% endblock %}

bulletinboard/templates/bulletinboard/threadIndex.html
{% extends "bulletinboard/base.html" %}
{% block title %} Thread Index - {{thread.name}}{% endblock %}
{% block body %}
    <header class="board-header">
        <a href="/bulletinboard/" class="link"> Home </a>
        >
        <a href="{% url 'bulletinboard:board' thread.board.id %}" class="link">{{thread.board.name}}</a>
        &nbsp;<img src="{{MEDIA_URL}}{{thread.board.icon}}" alt="Board Icon" class="header-board-icon" />
    </header>
    <!-- check if the user type is moderator or administrator, if yes, display buttons for locking/unlocking and marking sticky or not -->
    <header class="thread-header">
    {{thread.name}}
    <div class="thread-controls">
        {% if perms.bulletinboard.lock_thread %}
            {% if profile.is_banned == False %}
                <a href="{% url 'bulletinboard:sticky_not_sticky' thread.board.id thread.id %}">
                    {% if thread.thread_type == '1' %}
                        <img src="{{STATIC_URL}}images/pin.png" alt="Sticky Thread" class="header-image-button" title="Mark as Not Sticky" />
                    {% else %}
                        <img src="{{STATIC_URL}}images/unpin.png" alt="Not Sticky Thread" class="header-image-button" title="Mark as Sticky" />
                    {% endif %}
                </a>
                <a href="{% url 'bulletinboard:lock_unlock_thread' thread.board.id thread.id %}">
                    {% if thread.is_locked == False %}
                        <img src="{{STATIC_URL}}images/unlock.png" alt="Unlocked Thread" class="header-image-button" title="Click to Lock" />
                    {% else %}
                        <img src="{{STATIC_URL}}images/lock.png" alt="Locked Thread" class="header-image-button" title="Click to Unlock" />
                    {% endif %}
                </a>
            {% endif %}
            {% if profile.user_type == 3 or thread.user.user.username == user.username and profile.is_banned == False %}
                <a href="{% url 'bulletinboard:delete_thread' thread.board.id thread.id %}">
                    <img src="{{STATIC_URL}}images/trash.png" alt="Delete Thread" class="header-image-button" title="Delete Thread" />
                </a>
            {% endif %}
        {% endif %}
    </div>
    </header>   
    {% if posts %}
    <section>
        <table class="post-list">
            <tbody>
            {% for post in posts %}
            <tr>
                <td class="post-details">
                    <img src="{{MEDIA_URL}}{{post.user.avatar}}" class="post-avatar" alt="Avatar" />
                    <br />
                    <a class="link" href="{% url 'bulletinboard:other_profile' post.user.id %}">
                        {{post.user.user.username}}
                    </a>
                    <br />
                    {{post.date_posted}}
                </td>
                <td>
                    {{post.message|safe}}
                    <section class="editpost">
                        {% if profile.user.username == post.user.user.username and profile.is_banned == False and post.thread.is_locked == False %}
                            <a class="link" href="{% url 'bulletinboard:edit_post' thread.board.id thread.id post.id %}">
                                Edit Post
                            </a>    
                        {% endif %}
                    </section>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <section class="pagination">
            <form method="post" action="">
                {% csrf_token %}
                Go to page: 
                <select name="pagenumber">
                {% load bulletinboard_filters %}
                {% for page in posts.paginator.num_pages|get_range %}
                    <option value="{{page}}">{{page}}</option>
                {% endfor %}
                <select>
                <input type="submit" value=">>" name="gotopage" />
            </form>
        </section>
    </section>
    {% else %}
    <section class="empty-thread">
        <h2 class="no-list">No posts on this thread.</h2>
    </section>
    {% endif %}
    
    
    <!-- if the thread is locked, inform the user (the post form is not shown) -->
    {% if thread.is_locked %}
    <section class="locked-thread">
        <h2 class="no-list">
            <img src="{{STATIC_URL}}images/lock.png" class="header-image-button" alt="Locked Thread" />
            This thread is locked.
        </h2>
    </section>
    {% else %}
        <!-- if the thread is unlocked and the user is not banned, display the form -->
        {% if not profile.is_banned %}
        <section class="new-post-form">
            <hr />
            <h1 class="new-form-header">Add Post:</h1>
            <hr />
            <form action="" method="post">
                {% csrf_token %}
                <table>{{post_form.as_table}}</table>
                <input type="submit" value="Add Post" name="addpost" />
            </form>
        </section>
        <!-- if the user is banned, form is not shown -->
        {% else %}
        <section class="banned">
            <h2 class="no-list">
                <img src="{{STATIC_URL}}images/banned.png" class="header-image-button" alt="Banned" />
                You are banned from adding posts.
            </h2>
        </section>
        {% endif %}
    {% endif %}
    
{% endblock %}

bulletinboard/templates/bulletinboard/userProfile.html
    {% extends "bulletinboard/base.html" %}
{% block title %} User Profile {% endblock %}
{% block body %}
    <section class="user-profile">
        <header class="user-profile-header">
            <img src="{{MEDIA_URL}}{{profile.avatar}}" class="user-profile-avatar"/>
            About
            {% for user in user.userprofile_set.all %}
                <!-- check if the user has permission -->
                {% if perms.bulletinboard.ban_user %}
                    <!-- check if the user is not banned -->
                    {% if user.is_banned == False %}
                        <!-- check if the user logged in and the owner of the profile is not the same  and the owner of the profile is not an administrator -->
                        {% if profile.user.username != user.user.username and profile.user_type != 3 %}
                            <!-- display links for banning/permitting a user -->
                            <a href="{% url 'bulletinboard:ban_user' profile.id %}">
                                {% if profile.is_banned == False %}
                                    <img src="{{STATIC_URL}}images/banned.png" class="user-profile-button" title="Ban User" />
                                {% else %}
                                    <img src="{{STATIC_URL}}images/check.png" class="user-profile-button" title="Permit User" />
                                {% endif %}
                            </a>
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endfor %}
            {% if user.username == profile.user.username %}
                <a href="{% url 'bulletinboard:edit_user_profile' %}">
                    <img src="{{STATIC_URL}}images/edit-profile.png" class="user-profile-button" title="Edit Profile" />
                </a>
            {% endif %}
        </header>
        <br />
        <table class="user-profile-details">
            <tbody>
                <tr>
                    <td>Username: </td>
                    <td>{{profile.user.username}}</td>
                </tr>
                <tr>
                    <td>Gender: </td>
                    <td>{{profile.get_gender}}</td>
                </tr>
                <tr>
                    <td>Birthdate:</td>
                    <td>{{profile.birthdate}}</td>
                </tr>
                <tr>
                    <td>About Me: </td>
                    <td>{{profile.about_me}}</td>
                </tr>
                <tr>
                    <td>Interests: </td>
                    <td>{{profile.interests}}</td>
                </tr>
                <tr>
                    <td>Hometown:</td>
                    <td>{{profile.hometown}}</td>
                </tr>
                <tr>
                    <td>Present Location:</td>
                    <td>{{profile.present_location}}</td>
                </tr>
                <tr>
                    <td>User Type: </td>
                    <td>{{profile.get_type}}</td>
                </tr>
                <tr>
                    <td>Skype: </td>
                    <td>{{profile.skype}}</td>
                </tr>
                <tr>
                    <td>Yahoo! Messenger: </td>
                    <td>{{profile.ym}}</td>
                </tr>
                <tr>
                    <td>Website: </td>
                    <td>{{profile.website}}</td>
                </tr>
            </tbody>
        </table>
    </section>
    <br />
    <section class="user-profile">
    {% if posts %}
        <h2 class="label-header">POSTS:</h2>
        <table class="post-list">
            <tbody>
            {% for post in posts %}
                <tr>
                    <td class="profile-post-details ">
                        <img src="{{MEDIA_URL}}{{post.thread.board.icon}}" class="header-board-icon"/>
                        <a href="{% url 'bulletinboard:board' post.thread.board.id %}" class="link">
                            {{post.thread.board.name}}
                        </a>
                        <br /><br />
                        Thread: 
                        <a href="{% url 'bulletinboard:thread' post.thread.board.id post.thread.id %}" class="link">
                            {{post.thread.name}}
                        </a>
                        <br />
                        {{post.date_posted}}
                    </td>
                    <td>
                        {{post.message|safe}}
                        <section class="editpost">
                            {% if profile.user.username == user.username and profile.is_banned == False and post.thread.is_locked == False %}
                            <a class="link" href="{% url 'bulletinboard:edit_post' post.thread.board.id post.thread.id post.id %}">
                                Edit Post
                            </a>
                        {% endif %}
                        </section>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <section class="pagination">
            <form method="post" action="">
                {% csrf_token %}
                Go to page: 
                <select name="pagenumber">
                {% load bulletinboard_filters %}
                {% for page in posts.paginator.num_pages|get_range %}
                    <option value="{{page}}">{{page}}</option>
                {% endfor %}
                <select>
                <input type="submit" value=">>" name="gotopage" />
            </form>
        </section>
    {% else %}
        <h2>No Posts.</h2>
    {% endif %}
    </section>
{% endblock %}